-- ============================================================
-- 0056 — passport schema: isolated home for Samo Passport inside samoweb's
--        Supabase project (A = fheueuowbchsnsvbcgil), for the shared-login
--        merge. See docs/PASSPORT-MERGE.md.
--
-- WHAT: a faithful port of the live Samo Passport database (project B =
--   idwlabpbwiwgaoqwbozz) — generated from `pg_dump --schema-only` of B on
--   2026-07-21 — re-homed under a dedicated `passport` schema instead of
--   `public`.
--
-- WHY a separate schema: it is a structural firewall. Everything passport
--   owns is `passport.*`; a passport migration can NEVER touch
--   `public.pr_tickets` / `public.users` etc. Creating this schema does not
--   read or write anything in `public`, so applying it CANNOT affect
--   samoweb. Fully reversible: `drop schema passport cascade`.
--
-- SCOPE = Phase 0 (schema only). NO data (that's Phase 1, email re-keyed) and
--   deliberately NO trigger on `auth.users` (see the handle_new_user note
--   below) — so this is isolated to the new schema and safe on production.
--
-- TWO MANUAL STEPS AFTER APPLYING (nothing works from the app without them):
--   1. Supabase → Settings → API → "Exposed schemas" → add `passport`
--      (PostgREST won't serve passport.* over the anon key otherwise).
--   2. Point the passport app's supabase client at this schema, e.g.
--      createClient(url, key, { db: { schema: 'passport' } }) — a passport
--      CODE change made at cutover (Phase 3), not now.
-- ============================================================

create schema if not exists passport;

-- ---- reference tables (no user key) -------------------------------------
create table if not exists passport.continents (
  id        integer generated by default as identity primary key,
  name      text not null unique,
  color_hex text
);

create table if not exists passport.departments (
  id   integer generated by default as identity primary key,
  name text not null
);

create table if not exists passport.sub_departments (
  id            integer generated by default as identity primary key,
  department_id integer not null references passport.departments(id),
  name          text not null
);

-- ---- core tables --------------------------------------------------------
create table if not exists passport.activities (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  base_points_km     integer default 500,
  is_hourly          boolean default false,
  duration_hours     numeric,
  badge_url          text,
  continent_id       integer references passport.continents(id),
  is_marketing_bonus boolean default false,
  active_token       uuid default gen_random_uuid(),
  token_expires_at   timestamptz,
  created_at         timestamptz not null default timezone('utc'::text, now()),
  static_token       text,
  badge_name         text,
  department_id      integer,
  sub_department_id  integer
);

-- profiles.id = the passport user's auth.uid(). FK to auth.users (shared auth
-- in project A). Email is UNIQUE + NOT NULL — it is the stable bridge used to
-- re-key rows from project B during the Phase 1 data copy.
create table if not exists passport.profiles (
  id            uuid primary key references auth.users(id),
  full_name     text,
  email         text not null unique,
  total_km      integer default 0,
  tier_override text,
  updated_at    timestamptz not null default timezone('utc'::text, now())
);

create table if not exists passport.samo_years (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  started_at timestamptz not null default now(),
  ended_at   timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists passport.samo_seasons (
  id           uuid primary key default gen_random_uuid(),
  samo_year_id uuid not null references passport.samo_years(id) on delete cascade,
  name         text not null,
  started_at   timestamptz not null default now(),
  ended_at     timestamptz,
  created_at   timestamptz not null default now()
);

create table if not exists passport.seasons (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  scope       text not null,
  scope_id    integer,
  start_date  date not null,
  end_date    date not null,
  year        integer not null,
  created_at  timestamptz not null default now(),
  archived_at timestamptz,
  constraint seasons_scope_check check (scope in ('overall','department','subdepartment'))
);

create table if not exists passport.season_results (
  id         uuid primary key default gen_random_uuid(),
  season_id  uuid not null references passport.seasons(id) on delete cascade,
  user_id    uuid,
  full_name  text,
  email      text,
  points     integer not null default 0,
  created_at timestamptz not null default now()
);

-- certificates.activity_id is a PLAIN uuid (the activity FK was intentionally
-- dropped in B so a deleted activity keeps its certificate history).
create table if not exists passport.certificates (
  id             uuid primary key default gen_random_uuid(),
  activity_id    uuid not null,
  label          text not null,
  background_url text not null,
  name_x         numeric not null default 50,
  name_y         numeric not null default 55,
  font_size      numeric not null default 6,
  font_color     text not null default '#1f2d3d',
  created_at     timestamptz not null default now(),
  font_family    text not null default 'Prompt',
  season_id      uuid
);

-- one scan per user per activity (unique). id is integer (was a serial in B).
create table if not exists passport.scans (
  id                integer generated by default as identity primary key,
  user_id           uuid not null references auth.users(id),
  activity_id       uuid not null,
  scanned_at        timestamptz not null default timezone('utc'::text, now()),
  points_awarded    integer not null,
  samo_year_id      uuid,
  season_id         uuid,
  activity_name     text,
  department_id     integer,
  sub_department_id integer,
  constraint scans_user_id_activity_id_key unique (user_id, activity_id)
);

-- ---- indexes ------------------------------------------------------------
create index if not exists certificates_activity_id_idx on passport.certificates (activity_id);
create index if not exists certificates_season_idx      on passport.certificates (season_id);
create index if not exists samo_seasons_year_idx        on passport.samo_seasons (samo_year_id);
create index if not exists scans_season_idx             on passport.scans (season_id);
create index if not exists scans_year_idx               on passport.scans (samo_year_id);
create index if not exists season_results_season_idx    on passport.season_results (season_id);
create index if not exists season_results_user_idx      on passport.season_results (user_id);
create index if not exists seasons_scope_idx            on passport.seasons (scope, scope_id);

-- ---- points trigger (ported; pinned to the passport schema) -------------
-- On each scan: apply the activity's x2 marketing bonus and add the km to the
-- user's profile total. SECURITY DEFINER + an explicit search_path so the
-- unqualified table names resolve to passport.* (and can't be hijacked).
create or replace function passport.handle_new_scan()
returns trigger
language plpgsql
security definer
set search_path = passport
as $$
declare
  calculated_points integer;
  act_marketing_bonus boolean;
begin
  select is_marketing_bonus into act_marketing_bonus from activities where id = new.activity_id;
  calculated_points := new.points_awarded;
  if act_marketing_bonus then
    calculated_points := calculated_points * 2;
  end if;
  new.points_awarded := calculated_points;
  update profiles set total_km = total_km + calculated_points where id = new.user_id;
  return new;
end;
$$;

drop trigger if exists on_new_scan on passport.scans;
create trigger on_new_scan before insert on passport.scans
  for each row execute function passport.handle_new_scan();

-- handle_new_user() is ported for completeness but DELIBERATELY NOT attached
-- to auth.users here. In project A, auth.users already carries samoweb's own
-- signup triggers; adding a passport trigger that fires on EVERY signup (incl.
-- non-passport staff) — and could fail — risks bricking samoweb signups, the
-- exact 0041 failure class. Passport profiles are created by the Phase 1 data
-- copy; new post-cutover students are handled by a guarded mechanism decided
-- at cutover (app-side upsert on login, or a domain-gated trigger). Kept here
-- schema-pinned so that decision has the function ready.
create or replace function passport.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = passport
as $$
begin
  insert into passport.profiles (id, email, full_name, total_km)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', 0);
  return new;
end;
$$;

-- ---- tier view ----------------------------------------------------------
create or replace view passport.user_tiers as
  select p.id, p.full_name, p.total_km, p.tier_override,
    case
      when p.tier_override is not null then p.tier_override
      when p.total_km >= 7500 then 'The Ambassador'
      when p.total_km >= 2500 then 'The Voyager'
      when p.total_km >= 1000 then 'The Explorer'
      else 'Novice Traveler'
    end as final_tier,
    ((select count(*) from passport.scans s
       where s.user_id = p.id and s.scanned_at > (now() - interval '30 days')) >= 3) as has_travel_visa
  from passport.profiles p;

-- ---- RLS (permissive model ported verbatim from B) ----------------------
-- Passport uses the anon key with `using(true)` policies (its own STATE.md
-- documents this as intentional). `profiles` is the exception: public read,
-- own-row update only. departments / sub_departments have RLS ENABLED with NO
-- policy in B (⇒ not anon-readable) — replicated faithfully; the app doesn't
-- read them over the anon key. Tighten later if passport gets real admin auth.
alter table passport.activities      enable row level security;
alter table passport.certificates    enable row level security;
alter table passport.departments     enable row level security;
alter table passport.sub_departments enable row level security;
alter table passport.profiles        enable row level security;
alter table passport.samo_seasons    enable row level security;
alter table passport.samo_years      enable row level security;
alter table passport.scans           enable row level security;
alter table passport.season_results  enable row level security;
alter table passport.seasons         enable row level security;

do $$
declare t text;
begin
  -- full CRUD-open policies for the admin-model tables
  foreach t in array array['activities','certificates','samo_seasons','samo_years','scans','seasons'] loop
    execute format('drop policy if exists %I on passport.%I', t||'_read',   t);
    execute format('drop policy if exists %I on passport.%I', t||'_insert', t);
    execute format('drop policy if exists %I on passport.%I', t||'_update', t);
    execute format('drop policy if exists %I on passport.%I', t||'_delete', t);
    execute format('create policy %I on passport.%I for select using (true)',            t||'_read',   t);
    execute format('create policy %I on passport.%I for insert with check (true)',        t||'_insert', t);
    execute format('create policy %I on passport.%I for update using (true) with check (true)', t||'_update', t);
    execute format('create policy %I on passport.%I for delete using (true)',             t||'_delete', t);
  end loop;
end $$;

-- season_results: read/insert/delete open, no update (matches B)
drop policy if exists season_results_read   on passport.season_results;
drop policy if exists season_results_insert on passport.season_results;
drop policy if exists season_results_delete on passport.season_results;
create policy season_results_read   on passport.season_results for select using (true);
create policy season_results_insert on passport.season_results for insert with check (true);
create policy season_results_delete on passport.season_results for delete using (true);

-- profiles: public read, own-row update
drop policy if exists profiles_read_all   on passport.profiles;
drop policy if exists profiles_update_own on passport.profiles;
create policy profiles_read_all   on passport.profiles for select using (true);
create policy profiles_update_own on passport.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- ---- grants + PostgREST access (RLS still gates rows) -------------------
grant usage on schema passport to anon, authenticated;
grant all on all tables    in schema passport to anon, authenticated;
grant all on all sequences in schema passport to anon, authenticated;
grant all on all functions in schema passport to anon, authenticated;
alter default privileges in schema passport grant all on tables    to anon, authenticated;
alter default privileges in schema passport grant all on sequences to anon, authenticated;
alter default privileges in schema passport grant all on functions to anon, authenticated;
