-- ============================================================
-- 0106 — re-publishing must not eat photos that only exist in the archive.
--
-- THE HAZARD 0105 CREATED. Before 0105 the current year rendered from the live
-- tree, so its archive was a write-only curiosity and `publish_team_term`
-- replacing it wholesale cost nothing. After 0105 the current year IS its
-- snapshot, so "แก้ไขรายชื่อ/รูป" on the current year is a normal thing to do —
-- and the moment the live tree changes, the admin is prompted to เผยแพร่ซ้ำ,
-- which DELETES the archive and rebuilds it from the live tree. Every portrait
-- uploaded through the archive editor would vanish.
--
-- The re-publish confirm does warn, but "confirmed" is not the same as "fine":
-- the cost of clicking through is re-uploading up to 401 portraits, and the
-- prompt to re-publish is generated BY US, right next to the button.
--
-- FIX: carry a photo forward when the live tree has none. Precedence is
--   live photo (if any)  >  the photo already in this year's archive  >  null
-- so จัดการทีม stays the source of truth when it has an opinion, and an
-- archive-only photo survives a rebuild instead of being silently dropped.
--
-- Matching is by `src_member_id` — the live team_members.id the archive row was
-- copied from — added here for exactly this. Matching on names instead would
-- lose the photo of anyone whose name was corrected, which is one of the two
-- things the archive editor exists to do.
--
-- NOT carried forward: full_name / nickname / position / is_board. Those are
-- what "re-publish" means — take the current tree's version. Only the photo is
-- special, because it is the one field the live tree frequently does NOT have.
--
-- BASED ON THE LIVE BODY of publish_team_term (0104 is its only definition —
-- checked with pg_get_functiondef first).
-- ============================================================

alter table public.team_archive_members
  add column if not exists src_member_id uuid;

comment on column public.team_archive_members.src_member_id is
  'The live team_members.id this row was snapshotted from. Audit breadcrumb + the '
  'key publish_team_term() uses to carry an archive-only photo across a '
  're-publish. Deliberately NO foreign key: the archive must survive the live '
  'member being deleted, which is the entire point of an archive.';

create index if not exists team_archive_members_src_idx
  on public.team_archive_members (year, src_member_id);

create or replace function public.publish_team_term(p_year integer)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_nodes   integer;
  v_members integer;
  v_kept    integer;
begin
  -- coalesce(..., false) is load-bearing. current_user_role() is NULL for a
  -- caller with no public.users row, and `null = any(...)` is NULL, so a bare
  -- `if not (...)` would evaluate `not null` = null, skip the raise, and run the
  -- privileged body. mistakes.md: "null in (...) makes a raise-on-unauthorized
  -- guard fail OPEN".
  if not coalesce(
       public.current_user_role() = any (array['vp_admin', 'dev'])
       or public.current_user_has_permission('team'), false) then
    raise exception 'publish_team_term: not authorized';
  end if;

  if p_year is null or p_year < 2500 or p_year > 2700 then
    raise exception 'publish_team_term: bad year %', p_year;
  end if;

  insert into public.team_terms (year) values (p_year)
    on conflict (year) do nothing;

  -- Stash the photos this year's archive already holds, keyed by the live member
  -- they came from. A temp table (not a CTE) because the delete below has to
  -- happen in between. ON COMMIT DROP so a re-run in the same session is clean.
  create temp table if not exists _pub_photos (
    src_member_id uuid primary key, photo_url text, photo_focus text
  ) on commit drop;
  delete from _pub_photos;
  insert into _pub_photos (src_member_id, photo_url, photo_focus)
  select distinct on (am.src_member_id) am.src_member_id, am.photo_url, am.photo_focus
    from public.team_archive_members am
   where am.year = p_year
     and am.src_member_id is not null
     and am.photo_url is not null
   order by am.src_member_id, am.id;

  -- Cascades to team_archive_members via node_id.
  delete from public.team_archive_nodes where year = p_year;

  -- `as materialized` is required, not stylistic: `mapped` is referenced twice
  -- and contains gen_random_uuid(). Inlined, each reference would generate a
  -- DIFFERENT uuid and every parent_id lookup would come back null, silently
  -- flattening the tree.
  with recursive live as (
    select n.id, n.parent_id, n.name, n.kind, n.position, n.is_board
      from public.team_nodes n
     where n.parent_id is null and n.is_public
    union all
    select c.id, c.parent_id, c.name, c.kind, c.position, c.is_board
      from public.team_nodes c
      join live l on c.parent_id = l.id
     where c.is_public
  ),
  mapped as materialized (
    select l.*, gen_random_uuid() as new_id from live l
  )
  insert into public.team_archive_nodes
        (id, year, src_id, parent_id, name, kind, position, is_board)
  select m.new_id, p_year, m.id,
         (select p.new_id from mapped p where p.id = m.parent_id),
         m.name, m.kind, m.position, m.is_board
    from mapped m;
  get diagnostics v_nodes = ROW_COUNT;

  -- Only members whose ตำแหน่ง made it into the archive, i.e. the public
  -- subtree. A member under a non-public node is not published live and must
  -- not become published by being archived.
  --
  -- Photo precedence: the live tree wins when it has one; otherwise fall back to
  -- whatever this year's archive already had for that same person.
  insert into public.team_archive_members
        (year, node_id, src_member_id, full_name, nickname, photo_url, photo_focus, position)
  select p_year, an.id, m.id, m.full_name, m.nickname,
         coalesce(m.photo_url,   p.photo_url),
         coalesce(m.photo_focus, p.photo_focus),
         m.position
    from public.team_members m
    join public.team_archive_nodes an on an.year = p_year and an.src_id = m.node_id
    left join _pub_photos p on p.src_member_id = m.id;
  get diagnostics v_members = ROW_COUNT;

  select count(*) into v_kept
    from public.team_archive_members am
    join _pub_photos p on p.src_member_id = am.src_member_id
    join public.team_members m on m.id = am.src_member_id
   where am.year = p_year and m.photo_url is null;

  update public.team_terms
     set published_at = now(), updated_at = now()
   where year = p_year;

  return jsonb_build_object('year', p_year, 'nodes', v_nodes,
                            'members', v_members, 'photos_kept', v_kept);
end;
$$;

revoke all on function public.publish_team_term(integer) from public;
revoke all on function public.publish_team_term(integer) from anon;
grant execute on function public.publish_team_term(integer) to authenticated;
